//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input/ConTest.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ConTest: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ConTest()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ConTest"",
    ""maps"": [
        {
            ""name"": ""Button"",
            ""id"": ""72b14850-20f0-41db-9670-bcd1e00931c5"",
            ""actions"": [
                {
                    ""name"": ""Circle"",
                    ""type"": ""Button"",
                    ""id"": ""a45dc56b-3e51-4b24-b207-66ad68121af0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e07ced1a-6aaf-4390-9cd3-0b6185aa213d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Button
        m_Button = asset.FindActionMap("Button", throwIfNotFound: true);
        m_Button_Circle = m_Button.FindAction("Circle", throwIfNotFound: true);
    }

    ~@ConTest()
    {
        UnityEngine.Debug.Assert(!m_Button.enabled, "This will cause a leak and performance issues, ConTest.Button.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Button
    private readonly InputActionMap m_Button;
    private List<IButtonActions> m_ButtonActionsCallbackInterfaces = new List<IButtonActions>();
    private readonly InputAction m_Button_Circle;
    public struct ButtonActions
    {
        private @ConTest m_Wrapper;
        public ButtonActions(@ConTest wrapper) { m_Wrapper = wrapper; }
        public InputAction @Circle => m_Wrapper.m_Button_Circle;
        public InputActionMap Get() { return m_Wrapper.m_Button; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ButtonActions set) { return set.Get(); }
        public void AddCallbacks(IButtonActions instance)
        {
            if (instance == null || m_Wrapper.m_ButtonActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ButtonActionsCallbackInterfaces.Add(instance);
            @Circle.started += instance.OnCircle;
            @Circle.performed += instance.OnCircle;
            @Circle.canceled += instance.OnCircle;
        }

        private void UnregisterCallbacks(IButtonActions instance)
        {
            @Circle.started -= instance.OnCircle;
            @Circle.performed -= instance.OnCircle;
            @Circle.canceled -= instance.OnCircle;
        }

        public void RemoveCallbacks(IButtonActions instance)
        {
            if (m_Wrapper.m_ButtonActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IButtonActions instance)
        {
            foreach (var item in m_Wrapper.m_ButtonActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ButtonActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ButtonActions @Button => new ButtonActions(this);
    public interface IButtonActions
    {
        void OnCircle(InputAction.CallbackContext context);
    }
}
